# .github/workflows/ci.yml
name: CI

on:
    push:
        branches: [main] # Runs on push to the main branch
    pull_request:
        branches: [main] # Runs on pull request to the main branch

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x] # Define Node.js versions to test against

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn install

            - name: Run tests
              env:
                  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
                  ETHEREUM_NETWORK: ${{ secrets.ETHEREUM_NETWORK }}
                  FROM: ${{ secrets.FROM }}
              run: yarn test

